[package]
name = "ndot"
version = "0.0.0"
edition = "2021"
license = "MIT"
authors = ["Akira Kawata"]
description = "ndot is a new dot command."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ndot"
path = "src/lib.rs"

[[bin]]
name = "ndot"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
env = "1.0.1"
env_logger = "0.11.6"
log = "0.4.26"
