name: ndot CI

on:
  push:
    branches: [ main ]
    paths:
      - 'ndot/**'
  pull_request:
    paths:
      - 'ndot/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ndot
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Run tests
        run: cargo test
      - name: Check formatting
        run: cargo fmt --check
